### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [paviro/ESPHome-ePaper-Calendar#1]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by paviro** [comment]
Hi @JacksonChen666 I am not sure yet which license I want to use on this one that is why there is none yet. I hope to add one soon.

**Comment by paviro** [comment]
License added.
