### ISSUE TITLE
Quotable.io no longer resolves

### ISSUE THREAD

**Issue by cromulus** [paviro/ESPHome-ePaper-Calendar#3]
It appears that the service is down? 

Thanks!

**Comment by paviro** [comment]
Yes unfortunately (see https://github.com/lukePeavey/quotable/issues) if it won't come back soon I will consider hosting this myself or removing the feature for now.

**Comment by cromulus** [comment]
Yeah: I get the weather and current date and ask GPT-4o to compose a haiku for me.

Speaking of which, I would love to display the current weather somewhere. Maybe upper lefthand corner?

**Comment by paviro** [comment]
Not in the scope of this one on my end sorry but feel free to contribute it! I am using https://github.com/paviro/esphome-weatherman-dashboard for weather.

**Comment by cromulus** [comment]
oooohhhh..... L train! Yesss.... I have a second inkplate!

**Comment by paviro** [comment]
API is back online!
